language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http
  - git clone https://github.com/fukamachi/quri ~/lisp/quri

script:
  - cl -l prove
       -e '(or (prove:run :dexador-test) (uiop:quit -1))'
