language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl

matrix:
  allow_failures:
    - LISP=cmucl

addons:
  apt:
    packages:
      - libc6-i386
      - default-jre
      - clisp
      - libc6-dev-i386
      - libffi-dev

install:
  # Roswell
  - curl -L https://raw.githubusercontent.com/fukamachi/roswell/abcl-opts/scripts/install-for-ci.sh | sh
  # nginx
  - curl -L http://nginx.org/download/nginx-1.8.0.tar.gz | tar xzf -
  - (cd nginx-1.8.0 && ./configure --prefix=$HOME/nginx && make && make install)
  # Libraries to use the latest version
  - git clone https://github.com/Rudolph-Miller/jonathan ~/lisp/jonathan
  - git clone https://github.com/fukamachi/clack
  # prove
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/nginx
    - $HOME/.config/common-lisp

before_script:
  - nginx -c "$TRAVIS_BUILD_DIR/t/nginx.conf" -p "$HOME/nginx"
  - ros --version
  - ros config

script:
  - run-prove dexador-test.asd
  - benchmark/bench
