language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl

addons:
  apt:
    packages:
      - default-jre

install:
  # Roswell
  - curl -L https://raw.githubusercontent.com/fukamachi/roswell/abcl-opts/scripts/install-for-ci.sh | sh
  # nginx
  - curl -L http://nginx.org/download/nginx-1.8.0.tar.gz | tar xzf -
  - (cd nginx-1.8.0 && ./configure --prefix=$HOME/nginx && make && make install)
  # Libraries to use the latest version
  - git clone https://github.com/Rudolph-Miller/jonathan ~/lisp/jonathan
  - git clone https://github.com/fukamachi/clack ~/lisp/clack
  - git clone https://github.com/rpav/fast-io ~/lisp/fast-io
  - git clone https://github.com/fukamachi/quri ~/lisp/quri
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http
  # prove
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/nginx
    - $HOME/.config/common-lisp

before_script:
  - nginx -c "$TRAVIS_BUILD_DIR/t/nginx.conf" -p "$HOME/nginx"
  - ros --version
  - ros config

script:
  - run-prove dexador-test.asd
  - benchmark/bench
